spring.application.name=SpringProject
spring.data.mongodb.host=localhost
spring.data.mongodb.port=27017
spring.data.mongodb.database=myuserDatabase
spring.security.user.name=user
spring.security.user.password=myPass
